<?php

namespace Database\Seeders;

use App\Models\JobRole;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JobRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $job_roles = array(
            "Project Manager",
            "Marketing Manager",
            "Customer Service Representative",
            "Data Scientist",
            "Cybersecurity Analyst",
            "Human Resources Manager",
            "Architect",
            "Chef",
            "Veterinarian",
            "Writer",
            "Photographer",
            "Videographer",
            "Editor",
            "Musician",
            "Actor",
            "Artist",
            "Filmmaker",
            "Lawyer",
            "Engineer",
            "Police Officer",
            "Software Developer",
            "UX/UI Designer",
            "Graphic Designer",
            "Content Creator",
            "Social Media Manager",
            "SEO Specialist",
            "Digital Marketing Specialist",
            "Network Administrator",
            "Cloud Engineer",
            "Game Developer",
            "DevOps Engineer",
            "Machine Learning Engineer",
            "AI Researcher",
            "Blockchain Developer",
            "Product Manager",
            "Business Analyst",
            "Financial Analyst",
            "Investment Banker",
            "Accountant",
            "Auditor",
            "Economist",
            "Actuary",
            "Insurance Agent",
            "Real Estate Agent",
            "Construction Manager",
            "Civil Engineer",
            "Mechanical Engineer",
            "Electrical Engineer",
            "Biomedical Engineer",
            "Chemical Engineer",
            "Aerospace Engineer",
            "Environmental Engineer",
            "Forensic Scientist",
            "Pharmacist",
            "Nurse",
            "Doctor",
            "Surgeon",
            "Dentist",
            "Paramedic",
            "Radiologist",
            "Psychologist",
            "Therapist",
            "Speech-Language Pathologist",
            "Physical Therapist",
            "Occupational Therapist",
            "Fitness Trainer",
            "Dietitian",
            "Nutritionist",
            "Bartender",
            "Waiter/Waitress",
            "Hotel Manager",
            "Event Planner",
            "Tour Guide",
            "Flight Attendant",
            "Pilot",
            "Air Traffic Controller",
            "Marine Biologist",
            "Zoologist",
            "Wildlife Conservationist",
            "Geologist",
            "Meteorologist",
            "Astronomer",
            "Astrobiologist",
            "Chemist",
            "Research Scientist",
            "Mathematician",
            "Statistician",
            "Teacher",
            "Professor",
            "Special Education Teacher",
            "Principal",
            "School Counselor",
            "Librarian",
            "Translator",
            "Interpreter",
            "Journalist",
            "TV Host",
            "Radio Presenter",
            "Voice Actor",
            "Comedian",
            "Stand-up Performer",
            "Tattoo Artist",
            "Fashion Designer",
            "Makeup Artist",
            "Hairstylist",
            "Interior Designer",
            "Furniture Designer",
            "Jewelry Designer",
            "Perfumer",
            "Craftsman",
            "Carpenter",
            "Plumber",
            "Electrician",
            "Mechanic",
            "Truck Driver",
            "Logistics Coordinator",
            "Supply Chain Manager",
            "Warehouse Supervisor",
            "Security Guard",
            "Firefighter",
            "Detective",
            "Military Officer",
            "Customs Officer",
            "Park Ranger",
            "Environmental Scientist",
            "Urban Planner",
            "Waste Management Specialist",
            "Ethical Hacker",
            "Drone Operator",
            "E-commerce Manager",
            "Robotics Engineer",
            "Nanotechnology Researcher",
            "Quantum Computing Scientist",
            "Agronomist",
            "Fisherman",
            "Rancher",
            "Florist",
            "Brewmaster",
            "Winemaker",
            "Tea Taster",
            "Coffee Roaster",
            "Gastronomist",
            "Molecular Gastronomy Chef",
            "Space Scientist",
            "Astrophysicist",
            "Biotechnologist",
            "Neuroscientist",
            "Geneticist",
            "Cosmetologist",
            "Life Coach",
            "Motivational Speaker",
            "Political Analyst",
            "Public Relations Specialist",
            "Non-Profit Director",
            "Fundraiser",
            "Humanitarian Aid Worker",
            "Crisis Manager",
            "Diplomat",
            "Corporate Trainer",
            "Legal Consultant",
            "Mediator",
            "Sports Coach",
            "Professional Athlete",
            "Esports Player",
            "Game Tester",
            "Board Game Designer",
            "Toy Designer",
            "Antique Appraiser",
            "Auctioneer"
        );

        foreach ($job_roles as $item) {
            # code...
            $create = new JobRole();
            $create->name = $item;
            $create->save();
        }
    }
}
