<?php

namespace Database\Seeders;

use App\Models\Profession;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $professions = [
            'Software Developer',
            'Web Designer',
            'Data Scientist',
            'Digital Marketer',
            'UX/UI Designer',
            'Network Administrator',
            'Content Creator',
            'Project Manager',
            'Graphic Designer',
            'Database Administrator',
            'Cybersecurity Analyst',
            'Systems Analyst',
            'Mobile App Developer',
            'Game Developer',
            'Technical Writer',
            'DevOps Engineer',
            'Cloud Architect',
            'Business Analyst',
            'UI/UX Developer',
            'Artificial Intelligence Engineer',
            'Machine Learning Engineer',
            'Full Stack Developer',
            'Front-End Developer',
            'Back-End Developer',
            'Blockchain Developer',
            'Security Consultant',
            'Data Engineer',
            'SEO Specialist',
            'Robotics Engineer',
            'Penetration Tester',
            'Software Architect',
            'Network Security Engineer',
            'IT Support Specialist',
            'Help Desk Technician',
            'QA Engineer',
            'Technical Support Engineer',
            'Solutions Architect',
            'Product Manager',
            'Scrum Master',
            'IT Consultant',
            'Data Analyst',
            'Chief Technology Officer (CTO)',
            'Electrical Engineer',
            'Mechanical Engineer',
            'Civil Engineer',
            'Aerospace Engineer',
            'Environmental Engineer',
            'Biomedical Engineer',
            'Chemical Engineer',
            'Industrial Engineer',
            'Automotive Engineer',
            'Telecommunications Engineer',
            'Hardware Engineer',
            'Interior Designer',
            'Architect',
            'Landscape Architect',
            'Construction Manager',
            'Surveyor',
            'Urban Planner',
            'Quantity Surveyor',
            'Structural Engineer',
            'Marine Engineer',
            'Petroleum Engineer',
            'Geologist',
            'Meteorologist',
            'Physicist',
            'Biochemist',
            'Microbiologist',
            'Pharmacist',
            'Physician',
            'Surgeon',
            'Nurse',
            'Dentist',
            'Veterinarian',
            'Physical Therapist',
            'Occupational Therapist',
            'Chiropractor',
            'Optometrist',
            'Psychologist',
            'Social Worker',
            'Radiologist',
            'Medical Lab Technician',
            'Nutritionist',
            'Speech Therapist',
            'Clinical Researcher',
            'Pharmaceutical Scientist',
            'Geneticist',
            'Epidemiologist',
            'Public Health Officer',
            'Paramedic',
            'Forensic Scientist',
            'Lawyer',
            'Judge',
            'Legal Assistant',
            'Paralegal',
            'Corporate Lawyer',
            'Criminal Lawyer',
            'Environmental Lawyer',
            'Patent Attorney',
            'Human Rights Lawyer',
            'Tax Attorney',
            'Real Estate Agent',
            'Property Manager',
            'Estate Planner',
            'Investment Banker',
            'Financial Analyst',
            'Accountant',
            'Auditor',
            'Actuary',
            'Tax Consultant',
            'Insurance Broker',
            'Stockbroker',
            'Economist',
            'Marketing Manager',
            'Advertising Manager',
            'Public Relations Specialist',
            'Sales Manager',
            'Copywriter',
            'Journalist',
            'Editor',
            'Publisher',
            'Media Planner',
            'Photographer',
            'Film Director',
            'Actor',
            'Voice Actor',
            'Producer',
            'Musician',
            'Music Producer',
            'Sound Engineer',
            'Event Planner',
            'Fashion Designer',
            'Chef',
            'Pastry Chef',
            'Sommelier',
            'Restaurant Manager',
            'Bartender',
            'Hotel Manager',
            'Flight Attendant',
            'Pilot',
            'Air Traffic Controller',
            'Travel Agent',
            'Tour Guide',
            'Translator',
            'Interpreter',
            'Teacher',
            'Professor',
            'Instructional Designer',
            'Curriculum Developer',
            'Librarian',
            'Research Scientist',
            'Anthropologist',
            'Sociologist',
            'Historian',
            'Archaeologist',
            'Political Scientist',
            'Diplomat',
            'International Relations Specialist',
            'Human Resources Manager',
            'Recruiter',
            'Training and Development Manager',
            'Compensation and Benefits Manager',
            'Logistics Manager',
            'Supply Chain Manager',
            'Procurement Specialist',
            'Operations Manager',
            'Warehouse Manager',
            'Quality Control Manager',
            'Health and Safety Officer',
            'Compliance Officer',
            'Risk Manager',
            'Corporate Trainer',
            'Fleet Manager',
            'Facilities Manager',
            'Maintenance Engineer',
            'Security Officer',
            'Firefighter',
            'Police Officer',
            'Detective',
            'Correctional Officer',
            'Military Officer',
            'Intelligence Analyst',
            'Customs Officer',
            'Diplomatic Security Officer',
            'Public Policy Analyst',
            'Political Campaign Manager',
            'Legislative Assistant',
            'Policy Advisor',
            'Fundraiser',
            'Philanthropy Advisor',
            'Nonprofit Manager',
            'Community Organizer',
            'Volunteer Coordinator',
            'Museum Curator',
            'Archivist',
            'Art Director',
            'Animator',
            'Video Game Designer',
            'Game Tester',
            'Game Producer',
            'E-Sports Manager',
            'Social Media Manager',
            'Influencer',
            'YouTuber',
            'Podcast Producer',
            'Fitness Trainer',
            'Personal Trainer',
            'Yoga Instructor',
            'Nutrition Coach',
            'Sports Coach',
            'Sports Analyst',
            'Sports Agent',
            'Athlete',
            'Referee',
            'Event Manager',
            'Talent Manager',
            'Business Consultant',
            'Entrepreneur',
            'Venture Capitalist',
            'Franchise Owner',
            'Startup Founder',
            'Retail Manager',
            'Merchandiser',
            'Buyer',
            'Store Manager',
            'Customer Service Representative',
            'Call Center Manager',
            'Help Desk Support',
            'Virtual Assistant',
            'Life Coach',
            'Career Counselor',
            'Financial Planner',
            'Wedding Planner',
            'Estate Agent',
            'Landscaper',
            'Electrician',
            'Plumber',
            'Carpenter',
            'Mechanic',
            'Welder',
            'Painter',
            'Locksmith',
            'Tailor',
            'Florist',
            'Hairdresser',
            'Makeup Artist',
            'Tattoo Artist',
            'Barber',
            'Cosmetologist'
        ];

        foreach ($professions as $profession) {
            # code...
            $data = new Profession();
            $data->name = $profession;
            $data->save();
        }
    }
}
