<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $skillsList = [
            "Communication Skills",
            "Critical Thinking",
            "Problem Solving",
            "Creativity",
            "Teamwork",
            "Leadership",
            "Adaptability",
            "Time Management",
            "Emotional Intelligence",
            "Decision Making",
            "Analytical Skills",
            "Project Management",
            "Collaboration",
            "Negotiation",
            "Conflict Resolution",
            "Networking",
            "Presentation Skills",
            "Strategic Planning",
            "Research",
            "Data Analysis",
            "Digital Literacy",
            "Python",
            "Java",
            "JavaScript",
            "C++",
            "Ruby",
            "PHP",
            "Swift",
            "Kotlin",
            "TypeScript",
            "HTML/CSS",
            "Cybersecurity",
            "AWS (Amazon Web Services)",
            "Azure",
            "Google Cloud Platform",
            "Kubernetes",
            "Docker",
            "TensorFlow",
            "PyTorch",
            "scikit-learn",
            "Keras",
            "R",
            "SAS",
            "SPSS",
            "Financial Literacy",
            "Marketing Strategy",
            "Sales",
            "Customer Service",
            "Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
            "Sketch",
            "Canva",
            "Adobe Premiere Pro",
            "Final Cut Pro",
            "DaVinci Resolve",
            "Content Writing",
            "Foreign Language Proficiency",
            "Public Speaking",
            "Sales",
            "Quality Assurance",
            "Figma",
            "Sketch",
            "Adobe XD",
            "React.js",
            "Angular",
            "Vue.js",
            "Node.js",
            "Django",
            "Flask",
            "Ruby on Rails",
            "ASP.NET",
            "React Native",
            "Flutter",
            "Xamarin",
            "Swift (iOS)",
            "Kotlin (Android)",
            "Social Media Management",
            "SEO (Search Engine Optimization)",
            "Supply Chain Management",
            "Public Relations",
            "Risk Management",
            "Coaching/Mentoring",
            "Learning Agility",
            "Crisis Management",
            "Health and Wellness",
            "Cultural Competence",
            "Blockchain Development",
            "Ethical Hacking",
            "Penetration Testing",
            "Machine Learning",
            "Deep Learning",
            "Natural Language Processing (NLP)",
            "Robotics",
            "Automation",
            "Augmented Reality (AR)",
            "Virtual Reality (VR)",
            "3D Modeling",
            "CAD (Computer-Aided Design)",
            "Game Development",
            "DevOps",
            "CI/CD Pipelines",
            "Agile Methodologies",
            "Scrum",
            "Jira",
            "Confluence",
            "Trello",
            "Git",
            "GitHub",
            "Bitbucket",
            "Version Control",
            "Unit Testing",
            "Integration Testing",
            "UI/UX Design",
            "Graphic Design",
            "Branding",
            "Motion Graphics",
            "Video Editing",
            "Audio Production",
            "Music Composition",
            "Event Planning",
            "Event Management",
            "Budgeting and Forecasting",
            "Stakeholder Management",
            "Vendor Management",
            "Contract Negotiation",
            "Business Analysis",
            "Financial Analysis",
            "Investment Management",
            "Cryptocurrency",
            "Cloud Computing",
            "IoT (Internet of Things)",
            "Big Data",
            "Data Mining",
            "Data Visualization",
            "Power BI",
            "Tableau",
            "Microsoft Excel",
            "SAP",
            "Oracle",
            "SQL",
            "MySQL",
            "PostgreSQL",
            "MongoDB",
            "NoSQL Databases",
            "Hadoop",
            "Apache Spark",
            "TensorFlow",
            "Data Governance",
            "GDPR Compliance",
            "Business Process Improvement",
            "Six Sigma",
            "Lean Manufacturing",
            "Change Management",
            "Human Resources Management",
            "Talent Acquisition",
            "Employee Relations",
            "Compensation and Benefits",
            "Diversity and Inclusion",
            "Corporate Social Responsibility",
            "Energy Management",
            "Environmental Sustainability",
            "SaaS (Software as a Service)",
            "PaaS (Platform as a Service)",
            "IaaS (Infrastructure as a Service)",
            "Telecommunications",
            "Network Security",
            "Firewall Configuration",
            "Wi-Fi Networks",
            "LAN/WAN",
            "VPN (Virtual Private Networks)",
            "Remote Work Tools",
            "Virtualization",
            "VMware",
            "Hyper-V",
            "Cloud Security",
            "Information Security Management",
            "Disaster Recovery Planning",
            "Incident Response",
            "Data Privacy",
            "Mobile App Development",
            "Cross-Platform Development",
            "Responsive Web Design",
            "Frontend Development",
            "Backend Development",
            "API Development",
            "WebSockets",
            "RESTful APIs",
            "GraphQL",
            "OAuth",
            "JSON",
            "XML",
            "SOAP",
            "Serverless Architecture",
            "Microservices",
            "Enterprise Resource Planning (ERP)",
            "Customer Relationship Management (CRM)",
            "Marketing Automation",
            "Email Marketing",
            "Content Management Systems (CMS)",
            "WordPress",
            "Joomla",
            "Drupal",
            "Shopify",
            "E-commerce",
            "Payment Gateway Integration",
            "Product Management",
            "Innovation Management",
            "Business Development",
            "Customer Success Management",
            "Technical Support",
            "ITIL (Information Technology Infrastructure Library)",
            "Compliance Auditing",
            "Legal Research",
            "Patent Law",
            "Copyright Law",
            "Trademark Law",
            "Tax Law",
            "Intellectual Property",
            "Litigation Support"
        ];

        foreach ($skillsList as $skill) {
            # code...
            $data = new Skill();
            $data->name = $skill;
            $data->save();
        }
    }
}
